info:
  name: Loan Applications - Create Draft
  type: http
  seq: 6

http:
  method: POST
  url: "{{base_url}}/loan-applications/draft"
  headers:
    - name: Content-Type
      value: application/json
  body:
    type: json
    data: |-
      {
        "loanType": "DSCR",
        "numberOfProperties": 1
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
