name: Local
variables:
  - name: base_url
    value: http://localhost:8000
  - name: email
    value: admin2
  - secret: true
    name: password
  - name: OPEN_AI_API_KEY
    value: ""
  - name: open_ai_ocr_model
    value: ""
  - name: local_email
    value: ""
  - name: local_password
    value: ""
