name: Local
variables:
  - name: base_url
    value: http://localhost:8000
  - name: email
    value: admin
  - secret: true
    name: password
  - name: OPEN_AI_API_KEY
    value: ""
  - name: open_ai_ocr_model
    value: ""
  - name: local_email
    value: ""
  - name: local_password
    value: ""
  - name: workflow_id
    value: ""
  - name: loan_id
    value: "10186"
  - name: workflow_run_id_phase_1
    value: ""
  - name: workflow_run_id_phase_2
    value: ""
  - name: workflow_run_id_phase_3
    value: ""
  - name: workflow_run_id_phase_4
    value: ""
  - name: workflow_run_id_phase_5
    value: ""
  - name: workflow_run_id_phase_6
    value: ""
  - name: workflow_run_id_phase_7
    value: ""
  - name: workflow_run_id_phase_8
    value: ""
  - name: workflow_run_id_phase_9
    value: ""
  - name: workflow_run_id_phase_10
    value: ""
  - name: workflow_run_id_phase_11
    value: ""
  - name: phase_summary_phase_1
    value: ""
  - name: phase_summary_phase_2
    value: ""
  - name: phase_summary_phase_3
    value: ""
  - name: phase_summary_phase_4
    value: ""
  - name: phase_summary_phase_5
    value: ""
  - name: phase_summary_phase_6
    value: ""
  - name: phase_summary_phase_7
    value: ""
  - name: phase_summary_phase_8
    value: ""
  - name: phase_summary_phase_9
    value: ""
  - name: phase_summary_phase_10
    value: ""
  - name: phase_summary_phase_11
    value: ""
  - name: borrower_eligibility_validation_id
    value: ""
  - name: access_token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg1NTQ1MDM0LCJpYXQiOjE3ODU0NTg2MzQsImp0aSI6ImJmNTE5MTQ1OGVjZDQ4Y2JhODhlOTcwYWE2ZjE0OTVmIiwidXNlcl9pZCI6MX0.puVvwkoIA-QJLl854NXEBg7o9hCA8XwNZKKxk8QAg1o
  - name: workflow_run_id
    value: 8fa73f70-e136-4996-9d57-731aff726450
  - secret: true
    name: aiuw_api_key
